### ISSUE TITLE
Prompt engineering pdf link missing

### ISSUE THREAD

**Issue by rdela** [adventofgenai/challenges#2]
https://github.com/adventofgenai/challenges/blob/c91f08d34bbc5accfc8d16aafa15b48195a6abc7/01.md?plain=1#L10C319-L10C381

> here is a pdf on prompting for stable diffusion I found online

Did you mean to link something here @rahulunair ?

**Comment by rdela** [comment]
There is https://github.com/adventofgenai/challenges/pull/1 

already, which links directly to https://cdn.openart.ai/assets/Stable%20Diffusion%20Prompt%20Book%20From%20OpenArt%2011-13.pdf 

but https://github.com/adventofgenai/resources/blob/d7151bb3df2b008be72919657afe357b07e20a1c/README.md?plain=1#L27C45-L27C106 

Links Stable Diffusion Prompt Book to https://openart.ai/promptbook 

Which will be evergreen and is what the cover suggests.

**Comment by rahulunair** [comment]
merged!, thank you.
